# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Termín')),
                ('title', models.CharField(max_length=255, verbose_name='Nadpis')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Udalosť',
                'verbose_name_plural': 'Udalosti',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Termín')),
                ('title', models.CharField(max_length=255, verbose_name='Nadpis')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Novinka',
                'verbose_name_plural': 'Novinky',
            },
        ),
    ]
